final_project/projekt/urls.py
from django.contrib import admin
from django.urls import path

from pubmap.views import MainPage, AddPub, AddReview, ShowAllPubs, LoginView, logout_view, AddUserView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPage.as_view()),
    path('addpub', AddPub.as_view()),
    path('addreview', AddReview.as_view()),
    path('showallpubs', ShowAllPubs.as_view()),
    path('login', LoginView.as_view()),
    path('logout', logout_view),
    path('signin', AddUserView.as_view())
]

final_project/pubmap/models.py
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.db import models



# Create your models here.
RATING = (
    (1, "spokojnie usiądziesz"),
    (2, "pośpiesz się"),
    (3, "jak masz szczęście, to coś znajdziesz"),
    (4, "postoisz"),
    (5, "nawet nie wejdziesz")
)


class Pub(models.Model):
    name = models.CharField(max_length=255)
    formatted_address = models.CharField(max_length=255)
    place_id = models.CharField(max_length=255, unique=True)
    formatted_phone_number = models.CharField(max_length=16, null=True)
    website = models.URLField(null=True)
    opening_hours = JSONField(blank=True, null=True)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.name


class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    rating = models.IntegerField(choices=RATING)
    posted = models.DateTimeField(auto_now_add=True)
    pub = models.ForeignKey(Pub, on_delete=models.CASCADE)
    comment = models.TextField(blank=True)

final_project/pubmap/forms.py
from django import forms
from django.contrib.auth.models import User

from pubmap.models import Pub, Review


class AddPubForm(forms.ModelForm):
    class Meta:
        model = Pub
        fields = '__all__'
        labels = {
            'name': 'Nazwa knajpy',
            'formatted_address': 'Adres',
            'formatted_phone_number': 'Numer telefonu',
            'website': 'Adres strony'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'formatted_address': forms.TextInput(attrs={'class': 'form-control'}),
            'formatted_phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'website': forms.TextInput(attrs={'class': 'form-control'}),
            'place_id': forms.HiddenInput(),
            'open_now': forms.HiddenInput(),
            'opening_hours': forms.HiddenInput(),
            'latitude': forms.HiddenInput(),
            'longitude': forms.HiddenInput(),
        }


class AddReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'
        labels = {
            'rating': 'Ocena',
            'pub': 'Wybierz knajpę',
            'comment': 'Komentarz'
        }
        widgets = {
            'comment': forms.TextInput(attrs={'class': 'form-control'}),
            'rating': forms.Select(attrs={"class": "form-control"}),
            'pub': forms.Select(attrs={"class": "form-control"}),
            'author': forms.HiddenInput()
        }


class LogInForm(forms.Form):
    username = forms.CharField(label="Login", required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Hasło", widget=forms.PasswordInput(attrs={'class': 'form-control'}), required=True)


class AddUserModelForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Hasło')
    password_again = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Hasło ponownie')

    class Meta:
        model = User
        fields = ['username', 'password', 'email']
        labels = {
            'username': 'Nazwa użytkownika',
            'email': 'Adres email'
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'})
        }

final_project/pubmap/views.py
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User

from django.views import View
from django.views.generic import CreateView

from pubmap.forms import AddPubForm, AddReviewForm, AddUserModelForm, LogInForm
from pubmap.models import Pub, Review


class MainPage(View):
    def get(self, request):
        places = Pub.objects.all()
        reviews = Review.objects.order_by('-posted')
        return render(request, 'pubmap/homepage.html', {"places": places, "reviews": reviews})


class AddPub(CreateView):
    form_class = AddPubForm
    model = Pub
    success_url = '/'


class AddReview(CreateView):
    form_class = AddReviewForm
    model = Review
    success_url = '/'


class ShowAllPubs(View):
    def get(self, request):
        pubs = Pub.objects.order_by('name')
        reviews = Review.objects.order_by('-posted')
        return render(request, 'pubmap/showallpubs.html', {"pubs": pubs, "reviews": reviews})


class AddUserView(View):
    def get(self, request):
        form = AddUserModelForm()
        return render(request, 'pubmap/signin.html', {'form': form})

    def post(self, request):
        form = AddUserModelForm(request.POST)
        if form.is_valid():
            user_exists = User.objects.filter(username=form.cleaned_data['username']).exists()
            if user_exists:
                return render(request, 'pubmap/error.html', {'msg': "Już istnieje taki użytkownik"})
            if form.cleaned_data['password'] != form.cleaned_data['password_again']:
                return render(request, 'pubmap/error.html', {'msg': "Hasła są różne"})
            form.cleaned_data.pop('password_again')
            User.objects.create_user(**form.cleaned_data)
            return HttpResponseRedirect('/')


class LoginView(View):

    def get(self, request):
        form = LogInForm()
        return render(request, 'pubmap/login.html', {"form": form})

    def post(self, request):
        form = LogInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
            else:
                return render(request, 'pubmap/error.html', {'msg': "Błędne dane logowania"})
        else:
            return render(request, 'pubmap/login.html', {"form": form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

final_project/pubmap/templates/pubmap/base.html
<!DOCTYPE html>
<html lang="PL-pl">
<head>
    <meta charset="UTF-8">
    <title>Pub Map</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="static/css/style.css">

</head>
<body>
 <div class="container">
     <div>
    {% if user.is_authenticated %}
   <p class="bg-secondary text-white text-center text-uppercase font-weight-bold mb-1">zalogowany jako {{ user.username }}</p>
         <button onclick="window.location.href='/logout'" class="btn btn-block btn-dark text-uppercase font-weight-bold mb-1">Wyloguj się</button>
    {% else %}
         <button onclick="window.location.href='/login'" class="btn btn-block btn-dark text-uppercase font-weight-bold mb-1">Zaloguj się</button>
         <button onclick="window.location.href='/signin'" class="btn btn-block btn-dark text-uppercase font-weight-bold mb-1">Zarejestruj się</button>
    {% endif %}
     </div>
        <hr>
 </div>

{% block content %} {% endblock %}

</body>
</html>

final_project/pubmap/templates/pubmap/error.html
{%  extends 'pubmap/base.html' %}
{% block content %}
        <link rel="stylesheet" href="static/css/style.css">
    <div class="container">
    <div class="row">
        <div class="col-md-14 mx-auto">
                <button onclick="window.location.href='/'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Strona główna</button>
    <h2 class="error"> {{ msg }} </h2>
        </div>
    </div>
{% endblock %}

final_project/pubmap/templates/pubmap/homepage.html
{% extends 'pubmap/base.html' %}
<link rel="stylesheet" href="static/css/style.css">
{% block content %}

{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-md-14 mx-auto">
            <button onclick="window.location.href='/addpub'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Dodaj knajpę</button>
            <button onclick="window.location.href='/addreview'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Dodaj opinię</button>
            <button onclick="window.location.href='/showallpubs'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Zobacz wszystkie knajpy</button>
        </div>
    </div>
</div>
    {% endif %}
<hr>

<div id="map"></div>
<script>
      function initMap() {
       var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 52.237049, lng: 21.017532},
          zoom: 13,
           styles:
           [
    {
        "featureType": "all",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "saturation": 36
            },
            {
                "color": "#000000"
            },
            {
                "lightness": 40
            }
        ]
    },
    {
        "featureType": "all",
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "visibility": "on"
            },
            {
                "color": "#000000"
            },
            {
                "lightness": 16
            }
        ]
    },
    {
        "featureType": "all",
        "elementType": "labels.icon",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 20
            }
        ]
    },
    {
        "featureType": "administrative",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 17
            },
            {
                "weight": 1.2
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#17191b"
            },
            {
                "lightness": 20
            },
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 21
            }
        ]
    },
    {
        "featureType": "poi.attraction",
        "elementType": "geometry",
        "stylers": [
            {
                "saturation": "11"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 17
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 29
            },
            {
                "weight": 0.2
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels.text",
        "stylers": [
            {
                "saturation": "23"
            },
            {
                "lightness": "23"
            },
            {
                "gamma": "4.64"
            },
            {
                "weight": "1.95"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 18
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 16
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 19
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#3b87a5"
            },
            {
                "lightness": 17
            }
        ]
    }
]
        });
          {% for place in places %}
          var lat_lng = {lat: {{place.latitude}}, lng: {{place.longitude}}};
          var marker = new google.maps.Marker({position: lat_lng, map: map});
          google.maps.event.addListener(marker, 'click', function() {
              var model = document.getElementById('info');
              model.innerHTML = "{{place.name}}. "+
                  "Adres: {{place.formatted_address}}. {% if place.formatted_phone_number != "undefined" %} Numer telefonu: {{place.formatted_phone_number}}. {% endif %}" +
                 "{% if place.opening_hours != Null %} Godziny otwarcia: {%for day in place.opening_hours %} {{day}}{%endfor%}; {% endif %} {% for review in reviews %}{% if place.id == review.pub_id %}" +
                     "Ostatni raport: Czy usiądziesz? {{ review.get_rating_display }}. Dodano: {{ review.posted }}. {% endif %} {% endfor %}";
              model.classList.toggle('show');
});
          {% endfor %}
      }
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap">
    </script>

<div class="container" id="cont">
    <div class="alert alert-dark alert-dismissible fade in" id="info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
</div>


{% endblock %}

final_project/pubmap/templates/pubmap/login.html
{% extends 'pubmap/base.html' %}
{% block content %}
<link rel="stylesheet" href="static/css/style.css">
<div class="container">
    <div class="row">
        <div class="col-md-14 mx-auto">
            <button onclick="window.location.href='/'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Strona główna</button>
        </div>
    </div>


<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-dark text-uppercase font-weight-bold mb-1" value="Zaloguj">
</form>

</div>

{% endblock %}

final_project/pubmap/templates/pubmap/pub_form.html
{% extends 'pubmap/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-md-14 mx-auto">
            <button onclick="window.location.href='/'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Strona główna</button>
            <button onclick="window.location.href='/addreview'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Dodaj opinię</button>
            <button onclick="window.location.href='/showallpubs'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Zobacz wszystkie knajpy</button>
        </div>
    </div>
<br>
<div>

<script src="/static/js/pubsearch.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places&callback=initAutocomplete&language=pl-PL"
         async defer></script>
<form>
    <label>Szukaj knajpy po nazwie:</label><input type="text" id='searchbar' class="form-control" placeholder="Wpisz nazwę">
</form>

    <form action="" method="post" id="review">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-dark text-uppercase font-weight-bold mb-1" value="Zapisz!">
    </form>

</div>
{% else %}
<p>Strona dostępna tylko dla zalogowanych użytkowników!</p>
{% endif %}
</div>
{% endblock %}

final_project/pubmap/templates/pubmap/review_form.html
{% extends 'pubmap/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-md-14 mx-auto">
            <button onclick="window.location.href='/'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Strona główna</button>
            <button onclick="window.location.href='/addpub'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Dodaj knajpę</button>
            <button onclick="window.location.href='/showallpubs'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Zobacz wszystkie knajpy</button>
        </div>
    </div>

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-dark text-uppercase font-weight-bold mb-2" value="Dodaj opinię">
    </form>
{% else %}
<p>Strona dostępna tylko dla zalogowanych użytkowników!</p>
{% endif %}
</div>
{% endblock %}

final_project/pubmap/templates/pubmap/showallpubs.html
{% extends 'pubmap/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-md-14 h-100 justify-content-center align-items-center mx-auto">
            <button onclick="window.location.href='/'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Strona główna</button>
            <button onclick="window.location.href='/addpub'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Dodaj knajpę</button>
            <button onclick="window.location.href='/addreview'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Dodaj opinię</button>
        </div>
    </div>
<div class="listview">
    {% for pub in pubs %}
        <dl>
        <h3> {{ pub.name }} </h3>
            <dt> Adres:    </dt>
            <dd>{{ pub.formatted_address }}</dd>
            {% if pub.formatted_phone_number != "undefined" %}
                <dt>  Numer telefonu: </dt>
                <dd>{{ pub.formatted_phone_number }}</dd>
            {% endif %}
            <dt>  Adres strony:  </dt>
            <dd><a href="{{ pub.website }}">{{ pub.website }}</a></dd>
            {% if pub.opening_hours != Null %}
                <dt>   Godziny otwarcia: </dt>
                {% for day in pub.opening_hours %}
                    <dd> {{ day }} </dd>
                {% endfor %}
            {% endif %}
            <div id="accordion">
                <div class="card">
                    <div class="card-header p-3 mb-2 bg-dark text-white">
                        <a class="card-link text-white" data-toggle="collapse" href="#collapse">
                            <dt>Raporty:</dt>
                        </a>
                    </div>
                    <div id="collapse" class="collapse" data-parent="#accordion">
                        <div class="card-body">
                            {% for review in reviews %}
                                <dd>
                                    {% if pub.id == review.pub_id %}
                                        <li>
                                            <dt>Czy usiądziesz?</dt>
                                            <dd>{{ review.get_rating_display }}</dd>
                                            <dt>Data dodania opinii:</dt>
                                            <dd>{{ review.posted }}</dd>
                                            <dt>Komentarz: </dt>
                                            <dd>{{ review.comment }}</dd>
                                            <dt>Autor raportu: </dt>
                                            <dd>{{ review.author }}</dd>
                                        </li>
                                    {% endif %}
                                </dd>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

            <button onclick="window.location.href='/addreview'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Dodaj opinię</button>

        </dl>
    {% endfor %}
{% else %}
<p>Strona dostępna tylko dla zalogowanych użytkowników!</p>
{% endif %}
    </div>
</div>


{% endblock %}

final_project/pubmap/templates/pubmap/signin.html
{% extends 'pubmap/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<p> Jesteś już zalogowany! </p>
{% else %}

<div class="container">
    <div class="row">
        <div class="col-md-14 mx-auto">
            <button onclick="window.location.href='/'" class="btn btn-dark text-uppercase font-weight-bold mb-2">Strona główna</button>
        </div>
    </div>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-dark text-uppercase font-weight-bold mb-1" value="Zarejestruj się">
</form>

</div>

{% endif %}
{% endblock %}